name: CI Pipeline

on:
  push:
    branches:
      - main # Altere para o nome da sua branch principal, se necessário
  pull_request:
    branches:
      - main # Altere para o nome da sua branch principal, se necessário

jobs:
  # Job de instalação e verificação do ambiente
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12" # Altere para a versão do Python que você está usando

      - name: Install dependencies
        run: |
          python -m venv one_venv
          source one_venv/bin/activate
          pip install -r requirements.txt

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

  # Job para rodar o Linting
  lint:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Activate virtual environment and run flake8
        run: |
          source one_venv/bin/activate
          pip install flake8
          flake8 src/ tests/

  # Job para rodar os testes
  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Activate virtual environment and run tests
        run: |
          source one_venv/bin/activate
          pytest tests/
