name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Setup do ambiente Miniconda
  setup:
    runs-on: ubuntu-latest
    steps:
      # Fase 1: Baixar o código
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Fase 2: Configurar Miniconda e Python
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yml
          python-version: 3.12
          activate-environment: miniconda_env
      
      # Fase 3: Instalar dependências do projeto
      - name: Install dependencies
        run: conda activate miniconda_env && pip install -r requirements.txt

      # Fase 4: Cache das dependências pip
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

  # Linting e formatação do código
  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: miniconda_env
      
      - name: Install linting tools
        run: conda activate miniconda_env && pip install flake8 black

      - name: Run flake8
        run: conda activate miniconda_env && flake8 src/ tests/

      - name: Check code format with Black
        run: conda activate miniconda_env && black --check src/ tests/

  # Testes e cobertura de código
  test:
    runs-on: ubuntu-latest
    needs: lint

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: '#R1040grau$'
          MYSQL_DATABASE: db_gerenciador_arquivos
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: miniconda_env

      - name: Install testing tools
        run: conda activate miniconda_env && pip install pytest pytest-cov

      - name: Run tests with coverage
        run: conda activate miniconda_env && pytest --cov=src --cov-report=xml --cov-report=term-missing tests/

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  # Verificação da cobertura mínima
  coverage:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: miniconda_env

      - name: Install coverage tool
        run: conda activate miniconda_env && pip install coverage

      - name: Check minimum coverage
        run: conda activate miniconda_env && coverage report --fail-under=80
