name: CI Pipeline

on:
  push:
    branches:
      - main # Altere para o nome da sua branch principal, se necessário
  pull_request:
    branches:
      - main # Altere para o nome da sua branch principal, se necessário

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # Altere para a versão do Python que você está usando

      - name: Install dependencies
        run: |
          python -m venv one_venv
          source one_venv/bin/activate
          pip install -r requirements.txt

      - name: Install flake8
        run: |
          source one_venv/bin/activate
          pip install flake8

      - name: Run flake8
        run: |
          source one_venv/bin/activate
          flake8 src/ tests/

      - name: Run Tests
        run: |
          source one_venv/bin/activate
          pytest tests/
