# Workflow CI para uma aplicação Python
name: Python Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Fazer o checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # Configurar o Python (versão 3.12.3 ou ajuste conforme necessário)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    # Instalar dependências
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Executar verificação de estilo de código com Flake8
    - name: Run lint checks
      run: |
        source .venv/bin/activate
        flake8 app

    # Executar testes com cobertura de código
    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest --cov=app --cov-report=xml

    # Enviar relatório de cobertura para o Codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
